language: java

jdk:
  - openjdk9
  
dist: trusty

notifications:
  email: false
  
# whitelist
branches:
  only:
    - master
    
sudo: false 

script: 
  mvn clean install cobertura:cobertura coveralls:report -Djmeter.lib.scope=compile
